# This is a conda environment file for the BCL (Brain Computer Lab) environment.

name: BCLenv
channels:
  - conda-forge
  - defaults

dependencies:
  # Core Python
  - python=3.10
  - pip

  # Jupyter
  - ipykernel
  - jupyter
  - ipywidgets

  # Data & computation
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - statsmodels
  - seaborn
  - matplotlib
  - networkx
  - xarray
  - h5py
  - netcdf4

  # EEG/MEG processing
  - mne

  # Other
  - psutil

  # Install these via pip
  - pip:
      - addict
      - asrpy
      - autoreject
      - colour
      - diskcache
      - eeglabio
      - h5io
      - hmp
      - isosurfaces
      - manimgl
      - manimpango
      - mapbox-earcut
      - meegkit
      - mne-icalabel
      - moderngl
      - moderngl-window
      - openpyxl
      - patsy
      - pydub
      - pyglet
      - pyglm
      - pymatreader
      - pyopengl
      - pyparsing
      - pyperclip
      - pyprep
      - pyqt5
      - pyriemann
      - requests
      - rich
      - screeninfo
      - shiboken2
      - skia-pathops
      - svgelements
      - sympy
      - torch
      - tqdm
      - unidecode
      - validators
      - xmltodict
