name: eeg-preproc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - jupyter
  - ipykernel
  - ipython
  - scikit-learn
  - h5py
  - seaborn
  - tqdm
  - statsmodels
  - xarray
  - pyyaml
  - pip:
    - mne==1.9.0
    - autoreject==0.4.3
    - pyprep==0.4.3
    - eeglabio==0.0.3
    - pymatreader==1.0.0
    - asrpy==0.0.3
    - nibabel